# Generated by Django 2.2.24 on 2023-03-15 01:38

from django.db import migrations

def fill_Flat_new_building_field(property, schema_editor):
    Flat = property.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year and flat.construction_year >= 2015:
            flat.new_building = True
            flat.save()
        else:
            flat.new_building = False
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20230315_0326'),
    ]

    operations = [
        migrations.RunPython(fill_Flat_new_building_field)
    ]

