# Generated by Django 3.2 on 2023-03-17 14:56

from django.db import migrations
import phonenumbers


def purify_owner_phone_number(property, schema_editor):
    Flat = property.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        parsed_phonenumber = phonenumbers.parse(
            flat.owners_phonenumber,
            'RU'
            )
        flat.owner_pure_phone = phonenumbers.format_number(
            parsed_phonenumber,
            phonenumbers.PhoneNumberFormat.E164
            )
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(purify_owner_phone_number)
    ]
