# Generated by Django 3.2 on 2023-03-17 15:34

from django.db import migrations
import phonenumbers


def purify_owner_phone_number(property, schema_editor):
    Flat = property.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        parsed_phonenumber = phonenumbers.parse(
            flat.owners_phonenumber,
            'RU'
            )
        if phonenumbers.is_valid_number(parsed_phonenumber):
            flat.owner_pure_phone = phonenumbers.format_number(
                parsed_phonenumber,
                phonenumbers.PhoneNumberFormat.E164
                )
            flat.save()


def move_backward(property, schema_editor):
    Flat = property.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_flat_liked_by'),
    ]

    operations = [
        migrations.RunPython(purify_owner_phone_number, move_backward)
    ]
