# Generated by Django 3.2 on 2023-03-17 16:34

from django.db import migrations


def load_owners(property, schema_editor):
    Flat = property.get_model('property', 'Flat')
    Owner = property.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            name=flat.owner,
            phonenumber=flat.owners_phonenumber,
            pure_phonenumber=flat.owner_pure_phone
            )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
        migrations.RunPython(load_owners)
    ]
