# Generated by Django 3.2 on 2023-03-18 03:21

from django.db import migrations


def add_owners(property, schema_editor):
    Flat = property.get_model('property', 'Flat')
    Owner = property.get_model('property', 'Owner')
    for owner, phone, pure_phone in Flat.objects.values_list(
        'owner',
        'owners_phonenumber',
        'owner_pure_phone'
        ):
        Owner.objects.get_or_create(
            name=owner,
            phonenumber=phone,
            pure_phonenumber=pure_phone
            )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
        migrations.RunPython(add_owners)
    ]
