# Generated by Django 3.2 on 2023-03-18 03:58

from django.db import migrations


def connect_flat_and_owners(property, schema_editor):
    Flat = property.get_model('property', 'Flat')
    Owner = property.get_model('property', 'Owner')
    flats = Flat.objects.values_list('owner', 'id')
    for flat_owner, flat_id in flats.iterator():
        owner = Owner.objects.filter(name=flat_owner)[0]
        owner.owned_flats.set([flat_id])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20230318_0621'),
    ]

    operations = [
        migrations.RunPython(connect_flat_and_owners)
    ]
