# Generated by Django 3.2 on 2023-03-18 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20230318_0658'),
    ]


    operations = [
        migrations.RemoveField(
            model_name='Flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='Flat',
            name='owners_phonenumber',
        ),
        migrations.RemoveField(
            model_name='Flat',
            name='owner_pure_phone',
        ),
    ]
